/**
 * --------------------------------------------------------------------------
 *                                 SBML4j
 * --------------------------------------------------------------------------
 * University of Tuebingen, 2020.
 * 
 * This code is part of the SBML4j software package and subject to the terms
 * and conditions defined by its license (MIT License). For license details
 * please refer to the LICENSE file included as part of this source code
 * package.
 * 
 * For a full list of authors, please refer to the file AUTHORS.
 */

/*
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.tts.api;

import java.io.IOException;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.tts.model.api.NetworkInventoryItem;
import org.tts.model.api.OverviewNetworkItem;

import com.fasterxml.jackson.databind.ObjectMapper;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-10-06T11:55:24.162Z[GMT]")
@Api(value = "overview", description = "the overview API")
public interface OverviewApi {

    Logger log = LoggerFactory.getLogger(OverviewApi.class);

    default Optional<ObjectMapper> getObjectMapper(){
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest(){
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "upload a set of genes and get a network connecting them", nickname = "createOverviewNetwork", notes = "This endpoint creates an overview network that contains all available genes from the input gene list. The given genes will be annotated with  the boolean given by the field annotationName. The overview network will contain all available relationships between genes and metabolites that are part of the network. The endpoint returns a networkInventoryItem of the created network.  It can be retrieved using the UUID in the GET /network endpoint. If baseNetworkUUID is omitted, the full model will be used. ", response = NetworkInventoryItem.class, tags={ "convenience", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "network created", response = NetworkInventoryItem.class),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 403, message = "The current user is forbidden from accessing this data") })
    @RequestMapping(value = "/overview",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<NetworkInventoryItem> createOverviewNetwork(@ApiParam(value = "The genes of interest, aka. the driver genes, to build a driver gene network with based on the network with uuid 'baseNetworkUUID'. If 'baseNetworkUUID' is omitted, the default network will be used.The genes of interest for which to build an overview network.\n" + 
    		"          The network is based on the network with uuid 'baseNetworkUUID'.\n" + 
    		"          If 'baseNetworkUUID' is omitted, the default network will be used." ,required=true )  @Valid @RequestBody OverviewNetworkItem overviewNetworkItem
,@ApiParam(value = "The user which requests the creation" ,required=true) @RequestHeader(value="user", required=true) String user
) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"relationTypes\" : [ \"stimulation\", \"stimulation\" ],\n  \"name\" : \"Example Network\",\n  \"organismCode\" : \"hsa\",\n  \"links\" : [ {\n    \"rel\" : \"graphml\",\n    \"href\" : \"http://example.com:8080/sbml4j/networks/d25f4b9-8dd5-4bc3-9d04-9af418302244?format=graphml\"\n  }, {\n    \"rel\" : \"graphml\",\n    \"href\" : \"http://example.com:8080/sbml4j/networks/d25f4b9-8dd5-4bc3-9d04-9af418302244?format=graphml\"\n  } ],\n  \"numberOfNodes\" : 0,\n  \"numberOfRelations\" : 6,\n  \"UUID\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\n  \"nodeTypes\" : [ \"polypeptide chain\", \"polypeptide chain\" ],\n  \"networkMappingType\" : \"REGULATORY\"\n}", NetworkInventoryItem.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default VcfApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    @ApiOperation(value = "retrieve a previously created overview network for a user by its name", notes = "Attempts to retrieve an overview network by the network name that was  given during creation using POST /overview. If the network is available (created and active) it gets returned in  graphml format. If the network is still being created (not active yet) the endpoint returns a 404 error. If the network could not be created, the endpoint returns a 403 error. ",
    		response = Resource.class, tags={ "convenience" })
        @ApiResponses(value = { 
            @ApiResponse(code = 200, message = "successful operation", response = Resource.class),
            
            @ApiResponse(code = 204, message = "Network is not ready yet"),
            
            @ApiResponse(code = 403, message = "The network with the provided name could not be created and is not available") })
        @RequestMapping(value = "/overview",
            produces = { "application/octet-stream" }, 
            method = RequestMethod.GET)
        default ResponseEntity<Resource> getOverviewNetwork(@ApiParam(value = "The user which requests the creation" ,required=true) @RequestHeader(value="user", required=true) String user
        		, @ApiParam(value = "The network name to get",required=true) @RequestParam(value = "name", required = true) String name) {
    	  if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
              if (getAcceptHeader().get().contains("application/json")) {
                  try {
                      return new ResponseEntity<>(getObjectMapper().get().readValue("\"\"", Resource.class), HttpStatus.NOT_IMPLEMENTED);
                  } catch (IOException e) {
                      log.error("Couldn't serialize response for content type application/json", e);
                      return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                  }
              }
          } else {
              log.warn("ObjectMapper or HttpServletRequest not configured in default NetworksApi interface so no example is generated");
          }
          return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    	
    }

}
